# Generated by Django 4.2.17 on 2025-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, verbose_name='Напишите ваше Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Напишите вашу почту')),
                ('password', models.CharField(max_length=120, verbose_name='Придумайте пароль')),
                ('password_confirm', models.CharField(max_length=120, verbose_name='Повторите пароль')),
            ],
        ),
    ]
