# Generated by Django 4.2.17 on 2025-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Напишите ваше Имя')),
                ('car_number', models.CharField(max_length=25, verbose_name='Напишите номер машины')),
                ('time', models.TimeField(verbose_name='Напишите время брони')),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
