# Generated by Django 4.2.17 on 2025-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_booking_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='column_number',
            field=models.CharField(default=12, max_length=25, verbose_name='Напишите колону'),
            preserve_default=False,
        ),
    ]
